# file: .github/workflows/hello-world.yml
name: hello-world
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания, их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest

    steps:
          # Клонируем репозиторий
          - uses: actions/checkout@v2
          # Устанавливаем Node.js
          - uses: actions/setup-node@v18
          # Ставим зависимости
          - run: make setup
          # Запускаем линтер
          - run: make lint
          # Запускаем тесты
          # у шагов может быть имя, иногда это помогает отладке
          # имя выводится на Github при просмотре сборки
          - name: run tests
            run: make test # name и run относятся к одной задаче, поэтому дефис ставится только перед name